# See https://pre-commit.com/ for usage and config
repos:
- repo: local
  hooks:
  - id: trailing-whitespace
    name: trailing whitespace
    stages: [commit]
    language: system
    entry: trailing-whitespace-fixer
    types: [python]

  - id: isort
    name: import sort
    stages: [commit]
    language: system
    entry: isort
    types: [python]
    args: ["--profile", "black"]

  - id: black
    name: format
    stages: [commit]
    language: system
    entry: black
    types: [python]

  - id: flake8
    name: lint
    stages: [commit]
    language: system
    entry: flake8
    types: [python]

  # - id: pydocstyle
  #   name: docstring style
  #   stages: [commit]
  #   language: system
  #   entry: pydocstyle
  #   types: [python]
  #   exclude: '^\S+\/tests?\/\S+'
  #   args: ["--ignore=D100,D203,D400,D415,D213"]

#  - id: mypy
#    name: type check
#    stages: [commit]
#    language: system
#    entry: mypy
#    types: [python]
#    exclude: setup.py

  # - id: pytest
  #   name: pytest
  #   stages: [commit]
  #   language: system
  #   entry: python -m pytest
  #   types: [python]
  #   pass_filenames: false

  # - id: pytest-cov
  #   name: pytest-cov
  #   stages: [push]
  #   language: system
  #   entry: python -m pytest --cov --cov-fail-under=40
  #   types: [python]
  #   pass_filenames: false