name: consulting-website
channels:
  - conda-forge
  - defaults
dependencies:
  - black=23.3.0
  - flake8=6.0.0
  - ipython=8.12.0
  - isort=5.12.0
  - pep8-naming=0.13.3
  - pip=23.1.1
  - pre-commit=3.2.2
  - pre-commit-hooks=4.4.0
  - pydantic=1.9.0
  - pydocstyle=6.3.0
  - pytest-cov=4.0.0
  - pytest=7.3.1
  - pyyaml=5.4.1
  - numpy=1.22.3
# Project-specific dependencies
  - python=3.10.13
  - scikit-learn=1.3.0
  - pip:
    - pandas==2.1.1
    - matplotlib==3.8.0
    - tqdm
    - GitPython==3.1.40
    - ipykernel==6.26.0
    - seaborn==0.13.0
    - torch==2.0.1
    - psycopg2-binary==2.9.9
    - SQLAlchemy==2.0.30